version: '3'

services:
  frontend:
    image: frontend-image
    ports:
      - "80:80"
    networks:
      - webnet

  backend:
    image: backend-image
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:
